### ISSUE TITLE
[RPi4] Unknown ARM architecture version: armv7-l-neon.

### ISSUE THREAD

**Issue by raidensnake** [RaspberryPiFan/device_brcm_rpi4#2]
Unable to compile android 10 due to the following error:
`build/make/core/combo/TARGET_linux-arm.mk:63: error: Unknown ARM architecture version: armv7-l-neon.`

**Comment by RaspberryPiFan** [comment]
I'm testing a fix, I'll upload it later.

**Comment by yang-neu** [comment]
Me too, BTW, I'm on  HOST_OS_EXTRA=Linux-4.4.0-17763-Microsoft-x86_64-Ubuntu-18.04.3-LTS

**Comment by RaspberryPiFan** [comment]
Change device/brcm/rpi3/BoardConfig.mk like this:

```
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a72
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
```

**Comment by RaspberryPiFan** [comment]
But you're using WSL, there are some problems with builing android in it.

**Comment by RaspberryPiFan** [comment]
@yang-neu Read  #3

**Comment by yang-neu** [comment]
Hi RaspberryPiFan

I much appreciate your prompt response.
"armv7-a-neon" works well.

Then I encountered the "Soong minibootstrap fails" same as Mr. Berisan.
Yes, I work on a WSL because my PC has some problems with VMWare.
But WSL works well with building Android 9 + Rpi3B+ so far.
Please refer to this project also.
https://github.com/brobwind/pie-device-brobwind-rpi3

Could you please help me resolve the "Soong minibootstrap fails."

**Comment by RaspberryPiFan** [comment]
I don't know why you get this error, but I'll try to find it out and customize more parts of the android building system.

**Comment by RaspberryPiFan** [comment]
Architecture fixed.
